### ISSUE TITLE
Loop wenn während dem Anpflanzen das Item ausgeht

### ISSUE THREAD

**Issue by fellwell5** [MasterZydra/WurzelimperiumBot#104]
Mir ist aufgefallen, dass der Bot in einen Loop läuft, wenn während dem Anpflanzen das Item leer wird.

Dann kommen sehr viele Meldungen mit:
"Im Garten 1 konnte nicht angepflanzt werden."
"Radieschen anpflanzen..."
"Im Garten 1 konnte nicht angepflanzt werden."
"Radieschen anpflanzen..."

Siehe Screenshots: https://imgur.com/a/A1ptExU

**Comment by MasterZydra** [comment]
Hi @fellwell5,
ich schau es mir später an.
