### ISSUE TITLE
Sonderzeichen im Syntax

### ISSUE THREAD

**Issue by xRuffKez** [MasterZydra/WurzelimperiumBot#15]
Das automated_script.py kann bei Übergabe der Syntax (z.B. Sonderzeichen im Passwort) fehlerhaft ausgeführt werden.

Lösung fürs erste:

Statt...
```5 Gertrude passwort!2016```
...sollte als Abhilfe...
```5 Gertrude "passwort!2016"```
...als Syntax genommen werden.

**Comment by MasterZydra** [comment]
Das ist meiner Meinung nach kein Bug von unserem Skript, sondern die Eigenheit vom Linux/Unix Terminal. 
Ein Lösungsansatz wäre das einfach in der Readme zu erwähnen bzw. Immer mit Anführungszeichen die Argumente zu übergeben. 

https://superuser.com/questions/163515/bash-how-to-pass-command-line-arguments-containing-special-characters

**Comment by xRuffKez** [comment]
Ok, kommt hin. Nutze kein Windows mit Py3
