### ISSUE TITLE
Code-Review for aquagarden, bees, portal login, bird and login bonus 

### ISSUE THREAD

**Issue by Pazze12** [MasterZydra/WurzelimperiumBot#16]
Ich habe mal in meinem fork ein feature-branch erstellt und alle Änderungen hochgeladen, mag einer vielleicht mal drüber schauen ob ich grobe Logik Fehler drin habe?

**Comment by MasterZydra** [comment]
Hi. Ich habe hierzu mal einen Pull Request erstellt. Dort werde ich mir das Anschauen und ggf. noch Anmerkungen ergänzen

**Comment by MasterZydra** [comment]
@Pazze12 ich habe mal grob drübergelesen. Ersteinmal danke für die ganzen hilfreichen Erweiterungen / Verbesserungen.
Wenn die Logik bei deinen Tests soweit funktioniert hat, sollte es passen. Ich habe keine groben Fehler gesehen, bis auf die Kommentare beim PR ;).

**Comment by Pazze12** [comment]
Perfekt ich bin morgen wieder daheim und beantworte alle Fragen bzw schicke die Änderungen

**Comment by MrFlamez** [comment]
Ich will mir das heute Abend auch mal ansehen. Habe die Änderungen bisher nur überflogen. Ich hoffe ich schaffe es. Auf jeden Fall ein riesen Dankeschön für Deine Arbeit. :)

**Comment by Pazze12** [comment]
Ich schaue auch gleich nochmal warum er nicht startet weil mein lokales Projekt geht, ist bestimmt noch ein Kopie/Paste Fehler drin als ich meins mit eurem gemerged habe.

**Comment by Pazze12** [comment]
Vielleicht für mich als Info noch es macht schon Sinn die Bienen, den Bonsai und die Vogelpost in extra File zu / Klassen zu packen oder? Dann wäre nur die Frage wenn man zum Beispiel die Spielerdaten ausliest wo muss dann zb die Funktion is-available hin - also bonsai oder bienenfarm oder zum spieler.py?
