### ISSUE TITLE
Anzahl der Gärten konnte nicht ermittelt werden

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#25]
```
Anzahl der Gärten konnte nicht ermittelt werden.
Entferne Unkraut aus allen Gärten...
Es gibt momentan nichts zu ernten.
```

Seit dem Mergen der PRs kommt die Meldung, dass die Anzahl der Gärten nicht ermittelt werden kann. Die nachfolgenden Schritte laufen trotzdem durch. 
@xRuffKez kannst du mal schauen was die Meldung auslöst?

**Comment by xRuffKez** [comment]
Ja, ich versuche das auch schon seit nach dem merge zu fixen. Es liegt an
der HTTPCommunication.py in der getInfoFromStats(). Es kann die Variable
für den Server nicht aufgelöst werden und wirft none zurück statt bspw.
wurzelimperium.de

David Hein ***@***.***> schrieb am So., 10. Juli 2022, 10:06:

**Comment by xRuffKez** [comment]
Und vermutlich auch die readUserDataFromServer()

**Comment by MasterZydra** [comment]
@xRuffKez Das Problem ist: `'WurzelBot' object has no attribute 'honig'`

**Comment by MasterZydra** [comment]
Ich habe einfach mal beim try-catch die Fehlermeldung ausgeben lassen

**Comment by xRuffKez** [comment]
Da war ich auch grade mit print dabei :D

**Comment by MasterZydra** [comment]
Habs behoben

**Comment by xRuffKez** [comment]
Du meinst im launchBot() oder?

**Comment by MasterZydra** [comment]
Ich habe den Commit verlinked

**Comment by xRuffKez** [comment]
Liegt aber schon auf Höhe von __initGardens

**Comment by MasterZydra** [comment]
`if self.honig.isHoneyFarmAvailable()` ist falsch, da `self.honig` nicht existiert. Richtig ist `self.spieler....`

**Comment by MasterZydra** [comment]
Bei der Fehlersuche ist es teilweise hilfreich bei der entsprechenden Stelle, wo man weiß, dass die Fehlermeldung kommt das `except:` durch `except Exception as e: print(e)` auszutauschen, um die eigentliche Fehlermeldung zu bekommen. 
@xRuffKez

**Comment by xRuffKez** [comment]
Wow, danke für den Tipp! Das erleichtert die Bugsuche erheblich.

**Comment by Pazze12** [comment]
Die Prüfung gibt es doch in der class Honig in Bienen.py

**Comment by MasterZydra** [comment]
Ja, aber es wird im Spieler gespeichert. Siehe https://github.com/MasterZydra/WurzelimperiumBot/blob/4f33316b12f7e8e023a996ce9146bba941a823b4/src/WurzelBot.py#L128

Dazu wird direkt die Funktion aus HTTP Connection genutzt.

**Comment by Pazze12** [comment]
Ah okay, ich hatte es in beiden da ich dachte wenn man die Spieler Daten abfragt möchte man es da auch wissen

**Comment by MasterZydra** [comment]
@Pazze12  Man will die Honig Klasse ja nur initialisieren, wenn die Bedienungen für die Verwendung erfüllt sind. Deswegen wird die Klasse ja nur erstellt, wenn dort ein True zurück kommt. 
Die Variable Honig im WurzelBot wurde zudem nie gesetzt. Deswegen kam auch der Fehler.
