### ISSUE TITLE
Neue Feature

### ISSUE THREAD

**Issue by Pazze12** [MasterZydra/WurzelimperiumBot#29]
Hi i'll try to add new feature on my list are:
- shroomgarden (water, plant, buy shrooms)
- bonsaigarden (buy equipment)
- birds (start jobs, finish jobs, feed birds, buy new birds)
- mining (start jobs, finish jobs, feed worker)
- snails (train, build candy, feed snail)

I have good progress with collect all data but currently i struggle hard with the shop.

Maybe u have some tips, i want to buy for example 1 salat from the shop

```
    def buyFromShop(self):
        headers = self.__getHeaders()
        server = self.__getServer()
        adresse = f'{server}stadt/shop.php?s=2'
        parameter = urlencode({'s': 2,
                               'page': 1,
                               'change_page_only': 0,
                               'produkt[0]': 2,
                               'preis[0]': 0.08,
                               'anzahl[0]': 1,
                               'produkt[1]': 3,
                               'preis[1]': 0.44,
                               'anzahl[1]': 0,
                               'produkt[2]': 5,
                               'preis[2]': 0.5,
                               'anzahl[2]': 0,
                               'produkt[3]': 6,
                               'preis[3]': 0.06,
                               'anzahl[3]': 0,
                               'produkt[4]': 9,
                               'preis[4]': 1.76,
                               'anzahl[4]': 0,
                               'produkt[5]': 12,
                               'preis[5]': 0.14,
                               'anzahl[5]': 0,
                               'produkt[6]': 14,
                               'preis[6]': 0.22,
                               'anzahl[6]': 0,
                               'produkt[7]': 36,
                               'preis[7]': 2.1,
                               'anzahl[7]': 0})
        print(headers)
        print(adresse)
        print(parameter)
        try:
            response, content = self.__webclient.request(adresse, 'POST', parameter, headers=headers)
            self.__checkIfHTTPStateIsOK(response)
            print(response)
            print(content)
        except:
            return ''
```
For later i guess ill create a list with items per shop available to iterate over the shops

Have u planned anything to add?

**Comment by Pazze12** [comment]
Wie kaufe ich zb 3 Äpfel? ^^

**Comment by MasterZydra** [comment]
Ich habe mir die Funktionsweise vom Shop noch nicht im Detail angeschaut. 
Ich würde hier vermutlich die Entwicklertools des Web Browsers nutzen und im Netzwerk-Reiter anschauen, was beim Kaufen im Shop passiert.

**Comment by MasterZydra** [comment]
Ich habe gerade mal geschaut. Beim Einkaufen im Bauernhof hast du ja schon die URL und die Daten. Bei der Pflanze die du kaufen willst, musst du nur die Anzahl anpassen und das ganze mit POST versenden.

Beim Shop für Bäume geht es mit einer Anfrage via POST an `https://s{server-nr}.wurzelimperium.de/stadt/shop.php?s=1`
Und auch hier einfach die Anzahl beim gewünschten Produkt anpassen. Hier wurde jetzt 1 Apfel gekauft: 
	"s": "1",
	"page": "1",
	"change_page_only": "0",
	"produkt[0]": "1",
	"preis[0]": "41.4",
	"anzahl[0]": "0",
	"produkt[1]": "4",
	"preis[1]": "30.96",
	"anzahl[1]": "1",
	"produkt[2]": "8",
	"preis[2]": "30",
	"anzahl[2]": "0",
	"produkt[3]": "10",
	"preis[3]": "7.6",
	"anzahl[3]": "0",
	"produkt[4]": "11",
	"preis[4]": "5.75",
	"anzahl[4]": "0",
	"produkt[5]": "13",
	"preis[5]": "62.4",
	"anzahl[5]": "0",
	"produkt[6]": "17",
	"preis[6]": "56.28",
	"anzahl[6]": "0",
	"produkt[7]": "19",
	"preis[7]": "68.4",
	"anzahl[7]": "0",
	"produkt[8]": "21",
	"preis[8]": "46.8",
	"anzahl[8]": "0",
	"produkt[9]": "67",
	"preis[9]": "22.1",
	"anzahl[9]": "0"

**Comment by MasterZydra** [comment]
Die IDs für die Produkte sind bereits im WurzelBot bei den Produkten gespeichert.
Testen müsste man mal, was wirklich relavant in der Anfrage ist. Evtl reicht es ja aus nur das Produkt mit Id und Anzahl zu senden ohne alle Produkte angeben zu müssen.

**Comment by Pazze12** [comment]
mhh ok bei mir hat der post nicht funktioniert und dann müsste mal wahrscheinlich vorher die shops einmal durch laden oder vordefiniert speichern, ich finde diese funktion wichtig da sie ein bestandteil bei der vogelpost, schneckenrennen und auch minenarbeit hat

**Comment by Pazze12** [comment]
```
Salat im Lager: 9508
Kaufe Salat:
=====================
Headers: {'Cookie': 'PHPSESSID=fjdikpnihhjl0v5b03dllplg0r; wunr=292026', 'Connection': 'Keep-Alive'}
adresse: https://s1.wurzelimperium.de/stadt/shop.php?s=2
parameter: 2=2&page=1&change_page_only=0&produkt%5B8%5D=32&preis%5B8%5D=3.78&anzahl%5B8%5D=5
response: {'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate', 'pragma': 'no-cache', 'vary': 'Accept-Encoding', 'content-type': 'text/html; charset=UTF-8', 'content-length': '21001', 'date': 'Wed, 28 Sep 2022 10:02:20 GMT', 'server': 'lighttpd/1.4.59', 'status': '200', '-content-encoding': 'gzip'}
======================
Salat nach Kauffunktion: 9508
```

**Comment by MasterZydra** [comment]
Müsste der Erste Parameter nicht s = 2 sein?

**Comment by Pazze12** [comment]
Kommt auf den Shop an

**Comment by MasterZydra** [comment]
Ich meine bei den Parametern:  
**2=2**&page=1&change_page_only=0&produkt%5B8%5D=32&preis%5B8%5D=3.78&anzahl%5B8%5D=5

**Comment by Pazze12** [comment]
der Request sieht aber okay aus da ich im response und content den bekomme den ich auch manuell im browser bekommen mit den networktools

**Comment by MasterZydra** [comment]
@Pazze12 hast du neue Erkenntnisse?

**Comment by Pazze12** [comment]
Ja, also die Vogelpost ist soweit fertig , der Portallogin geht und Gilden Bewerbung, Wunder spenden und den Luckymaulwurf aktivieren. Außerdem das erste Regal freischalten, den zweiten Garten kaufen. Müsste ich Mal in PRs zusammenfassen... Aber den Shop bekomme ich noch nicht hin 😂

**Comment by MasterZydra** [comment]
Das klingt ja schon nach sehr vielen praktischen Featuren. 👍️

**Comment by MasterZydra** [comment]
@Pazze12 Ich habe den Fehler beim Shop gefunden. Es hat der Content-Type gefehlt.
```python
def buyFromShop(self):
    headers = self.__getHeaders()
    headers['Content-Type'] = 'application/x-www-form-urlencoded'
    server = self.__getServer()
    adresse = f'{server}stadt/shop.php?s=2'
    parameter = urlencode({'s': 2,
                           'page': 1,
                           'change_page_only': 0,
                           'produkt[0]': 3, # some product id
                           'anzahl[0]': 1})
    ...
```

**Comment by Pazze12** [comment]
Wie würdest du jetzt am besten lösen? Also als Beispiel gebraucht wir ein "Gehweg 3" sollen wir eine Liste mit allen items inklusive Shop erstellen oder es vorher auslesen?

**Comment by MasterZydra** [comment]
Da die Produkte pro Shop unverändert bleiben dürften, wäre eine Liste ein sinnvoller Ansatz, wo wir pro Produkt den richtigen Shop zuordnen.

**Comment by Pazze12** [comment]
Okay dann bereite ich dies vor

**Comment by Pazze12** [comment]
pull request gestellt für den shop
