### ISSUE TITLE
[Feature] Unkraut vernichten

### ISSUE THREAD

**Issue by ghost** [MasterZydra/WurzelimperiumBot#3]
Moin,

ich möchte eine Funktion für den Bot einbauen, damit dieser das Unkraut in den Gärten vernichtet.
Wie bekomme ich die ID's aus der json der Gärten?

**Comment by MrFlamez** [comment]
Ich habe gerade ein Commit gemacht mit den Änderungen um das Unkraut zu entfernen. Ich weiß nicht wann das im Repo auftaucht oder ob das noch freigeschaltet werden muss. Da schiel ich mal in Deine Richtung @MasterZydra

**Comment by MasterZydra** [comment]
@MrFlamez die Einladung ist raus. Damit solltest du Pushen können

**Comment by MrFlamez** [comment]
Habe meine Änderungen ins Repository gepusht.

@xRuffKez 
Neue Methode des Wurzelbots "removeWeedInAllGardens". Damit wird jegliches Unkraut entfernt. Kann auch für jeden Garten separat ausgeführt werden. Für den Garten heißt die Methode "removeWeed".
