### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Bearexe** [MasterZydra/WurzelimperiumBot#31]
Hey, ich versuche seit 2-3 Tagen das ganze zum laufen zu bringen erst mit Version 3.11 von Python jetzt mittlerweile auf 3.9 runter da es auf 3.11 nicht funktioniert hat mit lxml.
Nun bekomme ich ständig den fehler mit i18n dieser lautet: AttributeError: 'function' object has no attribute 'append' 
Habe schon halb Google durchsucht aber leider keine Lösung zu diesem Thema gefunden ich hoffe ihr könnt mir hierbei helfen.

Vielen Dank

**Comment by MasterZydra** [comment]
Hi,
ich habe versucht den Fehler über die GitHub Actions nachzustellen, jedoch ist hier alles ohne Fehler durchgelaufen.
Kannst du mir mehr Details geben z. B. welche Versionen der Abhängigkeiten du verwendest?

In den GitHub Actions werden die nachfolgenden Versionen genutzt:
PyYAML-6.0, httplib2-0.20.4, lxml-4.9.1, prettytable-3.5.0, pyparsing-3.0.9, python-i18n-0.3.9, wcwidth-0.2.5

**Comment by Pazze12** [comment]
Ich bin erst Montag wieder daheim , aber da werde ich es nochmal prüfen und
wenn du bist dahin keine Lösung hast helfe ich dir haha

**Comment by Bearexe** [comment]
habe auch alles davon drauf aber ich bekomme immer diesen AttributeError habe auch schon versucht nochmal alles zu deinstallieren und wieder neu drauf zu ziehen bringt aber leider keine Besserung.

**Comment by MasterZydra** [comment]
Kannst du die Fehlermeldung mit Stacktrace hier einfügen?

**Comment by Pazze12** [comment]
der Fehler scheint hier zu liegen bzw gibt es diesen Fehler noch:

```
Traceback (most recent call last):
  File "F:\Dokumente\GitHub\WurzelimperiumBot\automated_script.py", line 4, in <module>
    import src.Logger as logger
  File "F:\Dokumente\GitHub\WurzelimperiumBot\src\Logger.py", line 17
    logging.basicConfig(handlers=[logging.FileHandler(f'logs/wurzelbot {logtime}.log', 'a', 'utf-8')]
    ```

**Comment by MasterZydra** [comment]
Issue aufgrund fehlender Rückmeldung geschlossen
