### ISSUE TITLE
Erkennung von Bienenverfügbarkeit funktioniert nicht korrekt

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#40]
Beim Testen vom Bienen senden, wurden keine Bienen gesendet, obwohl schon drei Bienenstöcke freigeschaltet sind.
Die Logik in `HttpConnection.isHoneyFarmAvailable()` schaut, ob ein gestimmtes Geschenk vorhanden ist.
Bei mir ist diese Geschenk jedoch nicht im Trophäenschrank.

Hier müssen wir eine andere Prüfung finden.

**Comment by Pazze12** [comment]
Ah okay, ja das ist eine alte Prüfung, ich habe eine Idee für die neue
Prüfung...mache ich morgen früh gleich fertig

**Comment by Pazze12** [comment]
im neuen PR

**Comment by MasterZydra** [comment]
Behoben mit PR #41.
Vielen Dank @Pazze12  für den schnellen Fix, jetzt funktioniert es.
