### ISSUE TITLE
Account gebanned

### ISSUE THREAD

**Issue by Pazze12** [MasterZydra/WurzelimperiumBot#44]
Ich glaube ich habe einen IP-Bann bekommen xD

500 Accounts wurden gebannt LEL

**Comment by Pazze12** [comment]
24/7 xD
Bin selber schuld
Ich bin eigentlich nur traurig , dass auch mein Main gebannt wurde. 
Dort habe ich selten gebottet und sogar eine eigene ec2 instance verwendet

**Comment by Pazze12** [comment]
aber 81 Account haben überlebt haha

**Comment by Pazze12** [comment]
bin noch am überlegen nochmal einen hauptaccount zu machen , ansonsten könnte ihr die 81 accounts haben

**Comment by MasterZydra** [comment]
Also so wirklich 24/7 ohne Wartezeit?

**Comment by MasterZydra** [comment]
> bin noch am überlegen nochmal einen hauptaccount zu machen , ansonsten könnte ihr die 81 accounts haben

Wäre Schade dich hier zu verlieren. Du hast einige Features zum Bot beigetragen.
