### ISSUE TITLE
detection of Bot?

### ISSUE THREAD

**Issue by Cl0ckm4n** [MasterZydra/WurzelimperiumBot#46]
Hallo,
habt ihr einen Anhaltspunkt wie wahrscheinlich es ist, dass der Bot entdeckt wird und somit der Account gebannt wird?

Wäre möglicherweise die Verwendung von "undetected_chromedriver" sinnvoll?

Gruß

**Comment by MasterZydra** [comment]
Hallo @Cl0ckm4n,

bis auf die gebannten Accounts von Pazze12 (Issue https://github.com/MasterZydra/WurzelimperiumBot/issues/44) ist mir nichts gekannt.
Mein Account wird einmal pro Stunde vom Bot bewirtschaftet und wurde bisher noch nicht gesperrt.

So etwas wie "undetected_chromedriver" könnte hier schon sinnvoll sein. Es würde meines Erachtens ein großer Refactoring-Aufwand in der HTTPCommunication Datei bedeuten.

**Comment by Cl0ckm4n** [comment]
Ok das hört sich gut an, wenn der Bot bei dir dauerhaft im Einsatz ist und es bis dato keine Probleme gibt.
Dann werde ich die Implementierung mit chromedriver aufgrund des Aufwands erstmal hinten anstellen.
