### ISSUE TITLE
Request - BG lang, Servers

### ISSUE THREAD

**Issue by Fauster** [MasterZydra/WurzelimperiumBot#47]
Can you please add Bulgarian servers, so I will be able to involve myself.  

I have tried but looks like my code reading is not so good. 

Thanks.

**Comment by MasterZydra** [comment]
Hi @Fauster,

The server URL must be added to [this list](https://github.com/MasterZydra/WurzelimperiumBot/blob/1d8defb054325d14c157118a29247aa421746421/src/HTTPCommunication.py#L22C1-L27C2).
How does the URL look like if you are logged in?

**Comment by Fauster** [comment]
> Hi @Fauster,
> 
> The server URL must be added to [this list](https://github.com/MasterZydra/WurzelimperiumBot/blob/1d8defb054325d14c157118a29247aa421746421/src/HTTPCommunication.py#L22C1-L27C2). How does the URL look like if you are logged in?

Hey, 

I have tried but it is not working for some reason. 
Even had added a USA and a German account to test the bot - still no success. 

Either way : It is a subdomain as follows -  bg.molehillempire.com

Trying  over Debian 10/11/12 script never starts successfuly.

**Comment by Cl0ckm4n** [comment]
Hi, 
do you use the Portal Login? Because i think in the login process is a bug and maybe thats why you cant login...

**Comment by Fauster** [comment]
> Hi, do you use the Portal Login? Because i think in the login process is a bug and maybe thats why you cant login...

Hi Cl0ckm4n, 
yes my accounts are Portal Login. 
Also noted that LOG-s are showing only "Fail" to login. Nothing else -> where breaks.

**Comment by Cl0ckm4n** [comment]
Ok, i will push a fix for the portal login tomorrow. I still have to test a little bit...

**Comment by MasterZydra** [comment]
@Fauster Can you test it again?
Cl0ckm4n has fixed the portal login (https://github.com/MasterZydra/WurzelimperiumBot/commit/39888552d9ae524af1720b7e848106b314ec2fbf) and I added the URL (https://github.com/MasterZydra/WurzelimperiumBot/commit/a675af77e40de71c401f1dfdc9c7b553e6040e34)

**Comment by Fauster** [comment]
LOG: 

2024-01-05 16:51:38,177 - -------------------------------------------
2024-01-05 16:51:38,177 - Starting Wurzelbot for User ****** on Server No. *
2024-01-05 16:51:38,193 - An error occured while starting Wurzelbot.



Isn't it necessary to have *.lang.yaml as well?

**Comment by Cl0ckm4n** [comment]
Ok lets see if we can get this :)
This error means that the login itself fails...

1.) you pulled the recent changes from the repo, right?

2.) did you fill your loginData correctly, like:
user = 'Your_Username'
pw = 'Your_Password'
server = Your_Servernumber as integer
lang = 'bg'
**portalacc = True**

3.) i maybe found another little bug in the portallogin --> see branch "fix_portallogin" in my fork
adjust your code and test if it works now

4.) if not working to this point open the developer-tools in your browser (with F12) when logging in and send me the URL that look like this: 

GET | https://sxx1xx.wurzelimperium.de/logw.php?port=1&unr=xx7xx&portunr=xx6xx&hash=xx32xx&sno=xx1xx

!!! Please remove your private data, like unr, portunr, hash BUT tell me the count of characters for each variable (like i did xx6xx stands for 6 characters...)

**Comment by Fauster** [comment]
@Cl0ckm4n  So, I got yours : https://github.com/Cl0ckm4n/WurzelimperiumBot/tree/fix_portallogin    , 
setted the details and .... 
![123](https://github.com/MasterZydra/WurzelimperiumBot/assets/7107279/92d98e1a-1e2d-404b-b1d5-38d7c0543e56)

Only unr URL that I can see is : https://www.bg.molehillempire.com/login.php?logout=1&lastServer=1&unr=****8*** on the logout. Do not know how to use "Inspect" at Chrome to look for your request.

**Comment by Cl0ckm4n** [comment]
ok i have another idea...

go to HTTPCommunication.py and edit the serverurl for bg to this:

SERVER_URLS = {
    'de': '.wurzelimperium.de/',
    **'bg': '.bg.molehillempire.com/',**
    'en': '.molehillempire.com/',
    'us': '.molehillempire.com/',
    'ru': '.sadowajaimperija.ru/'
}

**Comment by Fauster** [comment]
> ok i have another idea...
> 
> go to HTTPCommunication.py and edit the serverurl for bg to this:
> 
> SERVER_URLS = { 'de': '.wurzelimperium.de/', **'bg': '.bg.molehillempire.com/',** 'en': '.molehillempire.com/', 'us': '.molehillempire.com/', 'ru': '.sadowajaimperija.ru/' }

I had the same idea couple of days ago. I had tried that already. Even going further as "hard wire" the domain / with without subdomain etc...

**Comment by Cl0ckm4n** [comment]
please try this version: https://github.com/Cl0ckm4n/WurzelimperiumBot/tree/bg-login

**Comment by Fauster** [comment]
> please try this version: https://github.com/Cl0ckm4n/WurzelimperiumBot/tree/bg-login

YOU MY MAN ARE MAGICIAN! 

IT DOES WORK!

May need some touches but it does work. Login flawless. Command output exists, even cyrilic is visual. 
Can you please explain what was the issue? Do not tell me it was the *.yml ....

**Comment by Cl0ckm4n** [comment]
Thats awesome :)

No the *.yml wasn't the issue. I just added it for your convenience and for further translations.

The main issue was:
The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.

**Comment by Fauster** [comment]
> Thats awesome :)
> 
> No the *.yml wasn't the issue. I just added it for your convenience and for further translations.
> 
> The main issue was: The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.

In general it was something that I could not solve myself. Phewww .... Now I will have to sort translation. 
Can I please request a "Linux installation" as well?

**Comment by Cl0ckm4n** [comment]
> > Thats awesome :)
> > No the *.yml wasn't the issue. I just added it for your convenience and for further translations.
> > The main issue was: The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.
> 
> In general it was something that I could not solve myself. Phewww .... Now I will have to sort translation. Can I please request a "Linux installation" as well?

The reason for the problem was that the bot was only tested for german servers. Yeah it was a bit tricky ^^

Linux... that already exists: https://github.com/MasterZydra/WurzelimperiumBot#installation-script-for-linux

**Comment by Fauster** [comment]
> > > Thats awesome :)
> > > No the *.yml wasn't the issue. I just added it for your convenience and for further translations.
> > > The main issue was: The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.
> > 
> > 
> > In general it was something that I could not solve myself. Phewww .... Now I will have to sort translation. Can I please request a "Linux installation" as well?
> 
> The reason for the problem was that the bot was only tested for german servers. Yeah it was a bit tricky ^^
> 
> Linux... that already exists: https://github.com/MasterZydra/WurzelimperiumBot#installation-script-for-linux

Will the "BG patch" merged or shall I smash fork?

**Comment by Cl0ckm4n** [comment]
> > > > Thats awesome :)
> > > > No the *.yml wasn't the issue. I just added it for your convenience and for further translations.
> > > > The main issue was: The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.
> > > 
> > > 
> > > In general it was something that I could not solve myself. Phewww .... Now I will have to sort translation. Can I please request a "Linux installation" as well?
> > 
> > 
> > The reason for the problem was that the bot was only tested for german servers. Yeah it was a bit tricky ^^
> > Linux... that already exists: https://github.com/MasterZydra/WurzelimperiumBot#installation-script-for-linux
> 
> Will the "BG patch" merged or shall I smash fork?

i only can create a pull request. The merging has to be done from @MasterZydra 
Lets wait for his answer :)
But, of course you can make a fork in the meantime.

**Comment by Fauster** [comment]
> > > > > Thats awesome :)
> > > > > No the *.yml wasn't the issue. I just added it for your convenience and for further translations.
> > > > > The main issue was: The login process expected a fixed character length of 7 for the unr. But the bg-unr had 8 characters so it couldn't be resolved.
> > > > 
> > > > 
> > > > In general it was something that I could not solve myself. Phewww .... Now I will have to sort translation. Can I please request a "Linux installation" as well?
> > > 
> > > 
> > > The reason for the problem was that the bot was only tested for german servers. Yeah it was a bit tricky ^^
> > > Linux... that already exists: https://github.com/MasterZydra/WurzelimperiumBot#installation-script-for-linux
> > 
> > 
> > Will the "BG patch" merged or shall I smash fork?
> 
> i only can create a pull request. The merging has to be done from @MasterZydra Lets wait for his answer :) But, of course you can make a fork in the meantime.

Smashing! Already working over translation. Amazing! Thank you so much!
