### ISSUE TITLE
Optimierung des AutomatedScripts für Pflanzen < 1x1

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#5]
- [ ] Ermittlung aller bepflanzbaren Felder
- [ ] Prüfen, ob aktuelle Pflanze (wenn < 1x1) überhaupt gepflanzt werden kann
- [ ] Liste der Pflanze mit geringstem Bestand erhalten

**Comment by xRuffKez** [comment]
Willst du abfragen wieviele Felder eine Pflanze braucht?

**Comment by MasterZydra** [comment]
Unter anderem. Die Idee ist folgende:
Das Script in automated_script.py bepflanzt den Garten automatisch mit der Pflanze mit dem geringsten Bestand in Lager.
Wenn dies nun aber eine Baum mit 4x4 oder z. B. Spargel mit 1x2 ist, kann es vorkommen, dass einzelne Felder nicht bepflanzt werden, da diese am Stück nur 1x1 haben.
In diesem Fall soll dort eine Pflanze mit einer Fläche von 1x1 gepflanzt werden.

**Comment by xRuffKez** [comment]
Ok, verstehe was du meinst, das Problem habe ich auch schon oft gesehen. Ich versuche da mal etwas. Eine Liste mit 1x1 Pflanzen die nach dem regulären Bepflanzen seperat nochmal durchgegangen wird.

**Comment by MasterZydra** [comment]
Ja. Das sollte die entsprechenden Werte enthalten.

**Comment by xRuffKez** [comment]
Hab ich gefixt

**Comment by MasterZydra** [comment]
Top 👍 Vielen Dank
