### ISSUE TITLE
Pläne

### ISSUE THREAD

**Issue by Pazze12** [MasterZydra/WurzelimperiumBot#6]
Hi cool, dass du die Entwicklung des Bots übernommen hast.
Ich habe auch angefangen mit der Vorlage von Flammez.
Bin aber bei Pytohn 2,7 geblieben.

Ich versuche mich gerade am Wassergarten, stoße aber dabei auf Probleme mit der Vererbung der Klasse Garden

aber ich denke ich werde mir deins mal forken und gleich hier weiter machen.

Hast du schonmal überlegt es eventuell so anzupassen, dass man es zb in PiContainer laufen lassen könnte und dabei einen Controller hat der Pods mit den jeweiligen Aufträgen starten kann. Also zb ein Account soll alle zwei Stunden seine Bienen los schicken. Dann würden die Slaves dem Controller nur die Infos des Accounts schicken wie Level,Geld,Zeiten und der Controller kann dann reagieren. Wäre halt für zb 100 Accounts sinnvoller als zb das MainSkript im Loop laufen zu lassen.

Ich habe akutell nur eine CSV mit 200 Accounts und lasse zb per Cronjob einmal am Tag den LoginBonus holen.

**Comment by MrFlamez** [comment]
Da die Weiterentwicklung gerade wieder etwas an Fahrt aufgenommen hat... kannst Du uns sagen, welche Probleme du mit der Vererbung der Klasse hast? Der Wassergarten benötigt eigene Implementierungen einzelner Methoden, da der Wassergarten stellenweise etwas spezieller ist.

Du hast 200 Accounts? Ich bin beeindruckt. Auf welchem Server?

Das mit dem PiContainer finde ich interessant. Gibt es dazu irgendwo ein paar Hintergrundinformationen, wie das Ganze funktioniert? Die Begriffe Controller, Pods und Slaves sagen mir in diesem Kontext leider nichts.

**Comment by Pazze12** [comment]
1. Thema

Das Wassergartenproblem konnte ich lösen, ich sitze gerade daran die unendliche Quest bzw allgemein das Thema Questen in Angriff zunehmen. Also dass man vorher einstellen kann zb im example.py, welche Quest priorisiert werden soll und dem entsprechend dann die Questziele ausgelesen werden und wenn die Produkte nicht im Lager sind angebaut werden / auf Wunsch auch einfach im Shop gekauft werden. Das Auslesen habe ich und ich überlege noch wie ich es am besten anbaue , in allen Gärten oder zb Honigquest nur in Garten 2 etc + Überschreibe bzw die Priorisierung für die Anbauen-Funktion fehlt noch.

Dann muss ich mein Zeug noch ins die neue Version von Zydra integrieren, da ich noch auf 2.7 Python arbeite.

Weitere Ziele wären noc hder Verkauf der Produkte am Markt/Wimps und die Vogelpost.

Habe auf jeden Fall durch dein @MrFlamez  schon sehr viel gelernt bzw da ich einiges nicht verstanden habe durch darauf folgende Tutorials.

2. Thema:

Ich habe mir mit Selenium ein kleines Script gebaut,was Accounts anlegt und die Email bestätigt -> output kommt dann in eine CSV also Name,Passwort,Email etc.

Da ich es eher als Spielerei, Limittests und Learning sehe , möchte keine anderen Spielern schaden. Die Accounts sind alle noch unter 20mio Punkte und auf verschiedenen Servern (1-10)

3. Thema

Die PiContainer-Idee ist erstaml nur eine Idee.
Also PiContainer ist im Endeffekt nur eine schöne GUI für Docker.
Meine Idee war am Anfang, dass man ja auslesen kann bzw am Ende des Script ausgeben kann wann der Account wieder "ready" ist, d.h. wann ein neuer Login notwendig wäre. Die Information muss ja dann zb in eine CSV oder an ein Anderes Script weitergeleitet werden. In meinem Fall mit mehreren Account macht die meiner Meinung sinn da eine Loop mit dem Script über alle Account schon eine Weile dauert und manche Account vielleicht Pflanzen angebaut haben die 40h und anderen die 40min brauchen, da ich ein Randomizer im anbauen drin habe, später Quest basierend. 

So nun kann zb das Masterscript was die Infos über die Zeiten kennt , zu den jeweiligen Zeit das Wurzelscript starten mit den jeweiligen Zugangsdaten zu dem Zeitpunkt wo der Account ready ist. 

3.x  Thema (overkill idee xD)

Um dies nun auch zu vervielfachen könnte man das Pythonscript in einen kleinen Docker-Container packen, also einen kleinen Dockerfile schreiben und dann könnte man theoretisch 25 Container gleichzeitig starten lassen und der komplette OverKill kommt mit einer Jenkins/Github oder Tekton pipeline die dann immer die Änderungen aus dem Git zieht und den Code aktuell hält. Hahaha 

slaves - wären die container die das script ausführen und dann wieder "zerstört werden"
controller - der Verwalter 
pod - die docker-container

**Comment by xRuffKez** [comment]
Rein aus Interesse: Warum nutzt du Py2?
Gibt einfache Erklärungen wie man Py2 in Py3 umschreiben kann.
