### ISSUE TITLE
merge changes from @Gosha-iv ?

### ISSUE THREAD

**Issue by Cl0ckm4n** [MasterZydra/WurzelimperiumBot#63]
is it possible to merge the changes from @Gosha-iv?

Especially i need the features implemented in the class Honey.

**Comment by MasterZydra** [comment]
Hi @Cl0ckm4n,

I merged the changes in the honey class from Gosha-iv.
I hope it helps you making progress.

**Comment by Cl0ckm4n** [comment]
Very nice, thanks :D

I'm gonna look into it :)
