### ISSUE TITLE
Portallogin

### ISSUE THREAD

**Issue by Pazze12** [MasterZydra/WurzelimperiumBot#7]
Hinzufügen eines Parameters

 `
class Session(object): 

    def __init__(self):
        """
        Initialisierung aller Attribute mit einem Standardwert.
        """
        self.__logSession = logging.getLogger('bot.Session')
        self.__sessionID = None
        self.__server = None
        self.__startTime = None
        self.__endTime = None
        self.__secure = ''

    def openSession(self, sessionID, server, secure=''):
        """
        Anlegen einer neuen Session mit allen notwendigen Daten.
        """
        self.__sessionID = sessionID
        self.__server = server
        self.__secure = secure

        self.__startTime = time.time()
        self.__endTime = self.__startTime + (self.__lifetime - self.__lifetime_reserve)

        sID = str(self.__sessionID)
        self.__logSession.info("Session (ID: " + sID + ") geöffnet")

    def getSecure(self):
        """
        Gibt die Https zurück.
        """
        return self.__secure
`

In der Httpcommunication.py

`
adresse = 'http' + str(self.__Session.getSecure()) + '://s' + str(
            self.__Session.getServer()) + '.wurzelimperium.de
`

Bei den Requests ergänzen, geht dann für beide login methoden

und für den Login habe ich:

UNR:

`
def __getunrFromURLPORT(self, url):
        """
        Ermittelt aus einer übergebenen URL den security token.
        """
        # token extrahieren
        split = re.search(r'.*portal/port_logw.php.*unr=([a-f0-9]{6}).*port', url)
        iErr = 0
        if split:
            tmpunr = split.group(1)
            if (tmpunr == ''):
                iErr = 1
        else:
            iErr = 1

        if (iErr == 1):
            self.__logHTTPConn.debug(tmpunr)
            raise JSONError('Fehler bei der Ermittlung des tokens')
        else:
            self.__unr = tmpunr
`

PORTUNR:

    `def __getportunrFromURLPORT(self, url):
        """
        Ermittelt aus einer übergebenen URL den security token.
        """
        # token extrahieren
        split = re.search(r'.*portal/port_logw.php.*portunr=([a-f0-9]{7})', url)
        iErr = 0
        if split:
            tmpportunr = split.group(1)
            if (tmpportunr == ''):
                iErr = 1
                else:
            iErr = 1

        if (iErr == 1):
            self.__logHTTPConn.debug(tmpportunr)
            raise JSONError('Fehler bei der Ermittlung des tokens')
        else:
            self.__portunr = tmpportunr`

PORTTOKEN:

`   
 def __getTokenFromURLPORT(self, url):
        """
        Ermittelt aus einer übergebenen URL den security token.
        """
        # token extrahieren
        split = re.search(r'.*portal/port_logw.php.*token=([a-f0-9]{32})', url)
        iErr = 0
        if split:
            tmpToken = split.group(1)
            if (tmpToken == ''):
                iErr = 1
        else:
            iErr = 1

        if (iErr == 1):
            self.__logHTTPConn.debug(tmpToken)
            raise JSONError('Fehler bei der Ermittlung des tokens')
        else:
            self.__token = tmpToken
`

LOGIN:

`
def logIn2(self, loginDaten):
        """
        Führt einen login durch und öffnet eine Session.
        """
        parameter = urlencode({'portserver': 'server' + str(loginDaten.server),
                               'portname': loginDaten.user,
                               'portpass': loginDaten.password,
                               'portsubmit': 'Einloggen'})

        headers = {'Content-type': 'application/x-www-form-urlencoded',
                   'Connection': 'keep-alive'}

        try:
            response, content = self.__webclient.request('https://www.wurzelimperium.de/portal/game2port_login.php', \
                                                         'POST', \
                                                         parameter, \
                                                         headers)
            # print response
            # print response['location']
            self.__getTokenFromURLPORT(response['location'])
            # print "Token " + str(self.__token)
            self.__getunrFromURLPORT(response['location'])
            # print "UNR " + str(self.__unr)
            self.__getportunrFromURLPORT(response['location'])
            # print "PortUNR: " + str(self.__portunr)
        except:
            raise

        headers = {'Content-type': 'application/x-www-form-urlencoded',
                   'Connection': 'keep-alive',
                   'Cookie': self.__unr}

        try:
            loginadresse = 'https://s1.wurzelimperium.de/logw.php?port=1&unr=' + self.__unr + '&portunr=' + self.__portunr + '&hash=' + self.__token + '&sno=1'
            # print "Loginadresse: " + str(loginadresse)
            response, content = self.__webclient.request(loginadresse, 'GET', headers=headers)
            # print "Login2content: " + str(content)
            # print "Login2response: " + str(response)
            self.__checkIfHTTPStateIsFOUND(response)
        except:
            raise
        else:
            # print response['set-cookie']
            cookie = SimpleCookie(response['set-cookie'])
            self.__Session.openSession(cookie['PHPSESSID'].value, str(loginDaten.server), "s")
            self.__cookie = cookie
            self.__userID = self.__unr
`

**Comment by Pazze12** [comment]
Sorry für die komische Formatierung bei Bedarf kopiere ich die einzeln Funktionen noch in File und lade die File als Attachment hoch.
Ich meine Main-Accounts über das Portal registriert und brauchte deshalb den Portallogin - der werden andere bzw mehrere Requests gemacht.

**Comment by MasterZydra** [comment]
@Pazze12 Ein Tipp für die Formatierung:

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

Damit wird der Quellcode sehr viel lesbarer dargestellt.

**Comment by MasterZydra** [comment]
Closed with PR #17 Merge improvements from Pazze12
