### ISSUE TITLE
Automatisierung der Exe Generierung

### ISSUE THREAD

**Issue by MasterZydra** [MasterZydra/WurzelimperiumBot#71]
@xRuffKez Wie wäre es eine GotHub Action zu erstellen, die die Exe Datei generiert, wenn ein Tag erstellt wird?

Was für ein Tool verwendest du dafür?

**Comment by xRuffKez** [comment]
Moin,
Das ist eine gute Idee. Ich verwende Pyinstaller. Das geht recht unkompliziert. Beachte, dass das Binary den Ordner "lang" braucht, der muss also beim compilen auch mit in die zip.

**Comment by MasterZydra** [comment]
Ich schau mir das die Tage mal an. Dann können wir einfach regelmäßig einen Tag erstellen, und die GitHub Action soll dann einen Release mit der Exe als Anhang erstellen.

**Comment by xRuffKez** [comment]
https://github.com/MasterZydra/WurzelimperiumBot/commit/9eea203c589652e939df9934133720c32ff7c35e

**Comment by MasterZydra** [comment]
> [9eea203](https://github.com/MasterZydra/WurzelimperiumBot/commit/9eea203c589652e939df9934133720c32ff7c35e)

Sehr gut. Der Trigger muss dann nur noch so geändert werden, damit nicht bei jedem Push, sondern nur beim Erstellen eines Tags gestartet wird.

Ich habe mir auch mal die anderen Änderungen von dir angeschaut.
Teilweise sind da die Imports von HTTPConnection rausgeflogen. Diese sind für Typehints und Vorschläge von VS Code gedacht.
Also bitte nicht alle löschen ;)

```Python
from src.core.HTTPCommunication import HTTPConnection

class Storage():
    def __init__(self, httpConnection: HTTPConnection):
```

**Comment by xRuffKez** [comment]
oh, sorry. dachte schon wozu das da ist :D

**Comment by MasterZydra** [comment]
@xRuffKez Verwendest du irgendwelche KI Tools für die Änderungen am Quellcode?

Die Logik funktioniert nämlich nicht mehr wie vorher z.B. bei der Anpflanzlogik in `automated_script.py`.
Die Logik soll eigentlich, wenn Pflanzen mit mehr als 1x1 Flächenbedarf nicht mehr angepflanzt werden können, Pflanzen mit 1x1 Flächenbedarf anpflanzt. Stattdessen bleiben nun die Felder einfach leer.

Ich habe es wieder gefixed.

**Comment by xRuffKez** [comment]
So in der Art. Ist ein Linter auf Steroide.
Tut mir leid, das ich die "automated_script.py" zerhauen habe, War etwas spät gestern Abend.

Kannst du bitte checken ob der Workflow richtig konfiguriert ist?

**Comment by MasterZydra** [comment]
Ich habe nach dem Zurücksetzen des Repos auf einen älteren Stand auch deine GitHub Action wieder hinzugefügt.

Dabei habe ich es so geändert, dass jede Nacht ein neuer Tag nach dem Schema "yy.mm.dd" erstellt wird, wenn für den aktuellen Stand noch kein Tag erstellt wurde. So wird, wenn es Änderungen gab, jede Nacht ein neuer Tag erstellt. Anschießend wird die Exe generiert.

**Comment by xRuffKez** [comment]
Ich küss dein Auge. Danke :)
