### ISSUE TITLE
Console.py Binary needs configfile

### ISSUE THREAD

**Issue by xRuffKez** [MasterZydra/WurzelimperiumBot#76]
Since the compiled console.py cannot be edited for credentials, we need a configfile for the Binary.

**Comment by MasterZydra** [comment]
Yes that would be one possibility. Another way could be optional arguments, like automated_script.

**Comment by MasterZydra** [comment]
Maybe a JSON file. And we could add an example file into the repo and put it into the zip file. 

Further more it would be useful to add an user guide into the README for the binaries. 

We also may can add Linux binaries to the build step.

**Comment by xRuffKez** [comment]
Im working on optional arguments
