### ISSUE TITLE
growPlantsInGardens pflanzt die falsche Anzahl Produkte an

### ISSUE THREAD

**Issue by MrFlamez** [MasterZydra/WurzelimperiumBot#8]
Der Funktion growPlantsInGardens kann übergeben werden, wie viel eines Produkts angebaut werden soll. Jedoch erfolgt das pro Garten. Das heißt, sollen 10 Salate angebaut werden, multiplizieren sich die 10 mit der Anzahl der Gärten. Besser wäre hier die Absolutzahl über alle Gärten hinweg zu berücksichtigen. So kann man die Gärten besser beplanen.

Zur Not kann man es noch konfigurierbar machen mit einem Flag. Absolute Zahl oder pro Garten.

**Comment by MasterZydra** [comment]
@MrFlamez Ist behoben. Nun wird die richtige Anzahl geplanzt.
