### ISSUE TITLE
Verträge erstellen

### ISSUE THREAD

**Issue by Joly0** [MasterZydra/WurzelimperiumBot#83]
Hallo, ich wollte wissen ob es möglich ist mit dem Bot Verträge zu erstellen und anzunehmen?

Mein Inventar ist komplett voll. Meine Idee war, dass der Bot, falls das Inventar voll ist, für das Item mit der höchsten Anzahl einen Vertrag erstellt und an sich selbst schickt, sodass der Inventar Slot frei ist. Außerdem wäre es hilfreich, wenn es ebenso hilfreich wäre, wenn der Bot die Verträge annehmen kann. So wäre es möglich zu checken welche Items ein Wimp kaufen will, der Bot könnte überprüfen ob die entsprechenden Items in Verträgen vorhanden sind und dann die Verträge annehmen.

**Comment by MasterZydra** [comment]
Hi @Joly0 

aktuelle ist das nicht vorgesehen. Ist aber eine gute Idee.

Zuerst müsste erst einmal die Logik implementiert werden, um einen Vertrag erstellen zu können. Danach könnte man darauf aufbauen.

**Comment by Joly0** [comment]
Hm, alles klar. Wenn ich python könnte, würde ich mir das mal anschauen, leider gehört das nicht zu meinem portfolio. So muss ich einfach abwarten

Danke dir aber schonmal für die Info :)

**Comment by MasterZydra** [comment]
Ich habe mal einen neuen Issue eröffnet, wo ich alle Feature-Wünsche/Ideen zusammentrage.
Siehe #84
